version: '3'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '80:80'
    networks:
      app:

  mysql:
    image: mysql:5.7.38
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=application
      - MYSQL_USER=application
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_STORAGE-./storage/mysql-data}:/var/lib/mysql:cached
    networks:
      app:

networks:
  app:
    driver: bridge
